src/Laplace/TrainingBundle/Entity/Type.php
<?php

namespace Laplace\TrainingBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity
 * @ORM\Table(name="`type`")
 * @UniqueEntity(fields="name")
 */
class Type
{

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=32, unique=true)
     * @Assert\NotBlank()
     * @Assert\Length(max=32)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=32)
     * @Assert\NotBlank()
     * @Assert\Length(max=32)
     */
    private $description;

    public function __construct($name = null, $description = null)
    {
        $this->name         = $name;
        $this->description  = $description;
    }

    public function getNameWithDescription()
    {
        return $this->getName() . ' : ' . $this->getDescription();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param  string $name
     * @return Type
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param  string $description
     * @return Type
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }
}

src/Laplace/TrainingBundle/Form/NeedType.php
<?php

namespace Laplace\TrainingBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * Représente le type d'entité Need pour la validation de formulaire.
 */
class NeedType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('title', 'text',
            array(
                'label' => 'Titre',
            )
        );
        $builder->add('description', 'textarea',
            array(
                'label'     => 'Description',
                'required'  => false,
            )
        );
        $builder->add('category', 'entity',
            array(
                'class'     => 'LaplaceTrainingBundle:Category',
                'property'  => 'name',
                'group_by'  => 'domain.name',
                'label'     => 'Catégorie',
                'required'  => false,
            )
        );
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            array(
                'data_class' => 'Laplace\TrainingBundle\Entity\Need',
            )
        );
    }

    public function getName()
    {
        return 'laplace_trainingbundle_needtype';
    }
}

src/Laplace/TrainingBundle/Controller/NeedController.php
<?php

namespace Laplace\TrainingBundle\Controller;

use Doctrine\DBAL\DBALException;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\Validator\Constraints as Assert;

use Laplace\TrainingBundle\Entity\Need;
use Laplace\TrainingBundle\Entity\NeedSubscription;
use Laplace\TrainingBundle\Entity\Event;

use Laplace\TrainingBundle\Form\NeedType;
use Laplace\TrainingBundle\Form\TypeSelectorType;

/**
 * Contrôleur de la partie "Besoins".
 */
class NeedController extends AbstractThreadAwareController
{

    /**
     * Affiche la page "Créer un nouveau besoin".
     *
     * @param  boolean  $admin
     * @return Response
     */
    public function createAction($admin)
    {
        $mngr = $this->getDoctrine()->getManager();

        // données initiales du formulaire
        $data = array(
            'need' => new Need(),
            'type' => null,
        );

        // construction du formulaire
        $builder = $this->createNamedFormBuilder('create_need', $data);
        $builder->add('need', new NeedType());

        if (!$admin) {
            $builder->add('type', new TypeSelectorType());
        }

        $builder->add('Envoyer', 'submit');

        // validation
        $form = $builder->getForm();
        if ($this->isNamedFormSubmitted('create_need', $form)) {
            if ($form->isValid()) {
                $data   = $form->getData();
                $user   = $this->getUser();

                // besoin
                $need = $data['need'];
                $need->setAuthor($this->getUser());
                $mngr->persist($need);
                $mngr->flush();

                // inscription
                if (!$admin) {
                    $subscription = new NeedSubscription();
                    $subscription->setNeed($need);
                    $subscription->setUser($this->getUser());
                    $subscription->setType($data['type']);
                    $mngr->persist($subscription);

                    // création d'un événement
                    $event = Event::create(Event::NEED_ADDED, $user, $need);
                    $mngr->persist($event);

                    // flush
                    $mngr->flush();
                }

                $this->flashInfo(
                    $admin ?
                        'Le besoin a été créé.' :
                        'Le besoin a été créé et ajouté à votre liste.'
                );

                $user_url = $this->generateUrl(
                    'laplace_training_view_need',
                    array(
                        'id' => $need->getId(),
                    )
                );
                $admin_url = $this->generateUrl(
                    'laplace_training_adm_view_need',
                    array(
                        'id' => $need->getId(),
                    )
                );
                $url = $admin ? $admin_url : $user_url;

                // notification
                $this->get('laplace.alert')->information(
                    $admin_url,
                    'Un nouveau besoin, intitulé "%s" ' .
                    'a été créé par %s.',
                    $need->getTitle(),
                    $this->getUser()->getFullName()
                );

                return $this->redirect($url);
            } else {
                $this->flashFormError();
            }
        }

        // échec de la validation : création de la vue
        return $this->render(
            'LaplaceTrainingBundle:Need:create.html.twig',
            array(
                'form' =>   $form->createView(),
                'admin' =>  $admin,
            )
        );
    }

    /**
     * Affiche la page "Voir un besoin".
     *
     * @param  type                                $admin
     * @param  \Laplace\TrainingBundle\Entity\Need $need
     * @return Response
     */
    public function viewAction($admin, Need $need = null)
    {
        $this->check($need);

        $mngr = $this->getDoctrine()->getManager();

        $parameters = array(
            'need' =>   $need,
            'admin' =>  $admin,
        );

        $thread_redirect = $this->createThreadView($parameters, 'thread_form');
        if ($thread_redirect != null) {
            return $thread_redirect;
        }

        //
        // Lorsqu'un utilisateur consulte la page, on doit lui afficher l'espace
        // échange avec les correspondants formation et lui proposer de gérer
        // son inscription à ce besoin (ajout, retrait, édition, etc.)
        //
        // Lorsqu'un administrateur consulte la page, il faut lui afficher
        // l'ensemble des discussions
        //

        $do_forms = array();

        if (!$admin) {
            $user = $this->getUser();
            $subscription = $mngr
                ->getRepository('LaplaceTrainingBundle:NeedSubscription')
                ->fetchOneByUserAndNeed($user, $need);

            $parameters['subscription'] = $subscription;

            // on affiche un formulaire différent si l'utilisateur a déjà
            // ajouté le besoin
            if ($subscription) {
                // il l'a déjà ajouté, on lui permet d'indiquer que ce besoin
                // est pourvu, de modifier le type ou de le retirer

                $do_forms[] = 'satisfied';
                $do_forms[] = 'edit';
                $do_forms[] = 'unsubscribe';
            } else {
                // il ne l'a pas déjà ajouté, on lui permet de le faire

                $do_forms[] = 'subscribe';
            }

            // récupération des discussions
            $parameters['threads'] = $mngr
                ->getRepository('LaplaceTrainingBundle:Thread')
                ->fetchByParticipantAndReference($user, $need);
        } else {
            // $admin is true
            $parameters['subscriptions'] = $mngr
                ->getRepository('LaplaceTrainingBundle:NeedSubscription')
                ->fetchByNeed($need);

            // récupération des discussions
            $parameters['threads'] = $mngr
                ->getRepository('LaplaceTrainingBundle:Thread')
                ->fetchByParticipantAndReference(null, $need);
        }

        $user_url = $this->generateUrl(
            'laplace_training_view_need',
            array(
                'id' => $need->getId(),
            )
        );
        $admin_url = $this->generateUrl(
            'laplace_training_adm_view_need',
            array(
                'id' => $need->getId(),
            )
        );
        $url = $admin ? $admin_url : $user_url;

        // Formulaire d'inscription
        if (in_array('subscribe', $do_forms)) {
            if ($this->doSubscribeForm($parameters, 'subscribe_form')) {
                $this->get('laplace.alert')->notice(
                    $admin_url,
                    '%s a ajouté le besoin "%s".',
                    $this->getUser()->getFullName(),
                    $need->getTitle()
                );

                return $this->redirect($url);
            }
        }

        // Formulaire d'édition d'une inscription
        if (in_array('edit', $do_forms)) {
            if ($this->doEditSubscriptionForm($parameters, 'edit_form')) {
                return $this->redirect($url);
            }
        }

        // Formulaire de retrait d'une inscription
        if (in_array('unsubscribe', $do_forms)) {
            if ($this->doUnsubscribeForm($parameters, 'unsubscribe_form')) {
                $this->get('laplace.alert')->notice(
                    $admin_url,
                    '%s a retiré le besoin "%s".',
                    $this->getUser()->getFullName(),
                    $need->getTitle()
                );

                return $this->redirect($url);
            }
        }

        // Formulaire pour indiquer que le besoin est pourvu
        if (in_array('satisfied', $do_forms)) {
            if ($this->doSatisfiedForm($parameters, 'satisfied_form')) {
                $this->get('laplace.alert')->notice(
                    $admin_url,
                    '%s a indiqué que le besoin "%s" était pourvu.',
                    $this->getUser()->getFullName(),
                    $need->getTitle()
                );

                return $this->redirect($url);
            }
        }

        return $this->render(
            'LaplaceTrainingBundle:Need:view.html.twig',
            $parameters
        );
    }

    /**
     * Affiche la page "Tous les besoins".
     *
     * @param  boolean  $admin
     * @return Response
     */
    public function viewAllAction($admin)
    {
        $mngr = $this->getDoctrine()->getManager();

        $domains = $mngr
            ->getRepository('LaplaceTrainingBundle:Domain')
            ->fetchAll();

        $needs = $mngr
            ->getRepository('LaplaceTrainingBundle:Need')
            ->fetchAll();

        // regrouper les besoins par catégories et domaines
        $groups = array(
            null => array(),
        );
        foreach ($needs as $need_info) {
            $cat = $need_info->getNeed()->getCategory();

            if ($cat == null) {
                $groups[null][] = $need_info;
            } elseif (isset($groups[$cat->getId()])) {
                $groups[$cat->getId()][] = $need_info;
            } else {
                $groups[$cat->getId()] = array($need_info);
            }
        }

        return $this->render(
            'LaplaceTrainingBundle:Need:view-all.html.twig',
            array(
                'domains'   => $domains,
                'groups'    => $groups,
                'admin'     => $admin,
            )
        );
    }

    /**
     * Affiche la page "Besoins personnels".
     *
     * @return Response
     */
    public function viewActiveSubscriptionsAction()
    {
        $mngr = $this->getDoctrine()->getManager();

src/Laplace/TrainingBundle/Resources/views/Need/create.html.twig
{%
    set container = admin ?
        'LaplaceCommonBundle::admin-page.html.twig' :
        'LaplaceCommonBundle::user-page.html.twig'
%}

{% embed container with { page: [ 'need', 'create' ] } %}

{% block PageTitle %}{{ parent() }} - Nouveau besoin{% endblock %}

{% block ContentTitle %}Nouveau besoin{% endblock %}

{% block ContentBody %}

<p>
    Avant de créer un besoin, <strong>vérifiez qu'il n'existe pas</strong> déjà dans
    la <a href="{{ path(laplace_training ~ 'all_needs') }}">liste de tous les besoins</a>.
    Le besoin nouvellement créé sera <strong>automatiquement ajouté</strong> à
    votre liste personnelle.
</p>

{{ form_start(form) }}

<fieldset>

    <legend>Créer un nouveau besoin</legend>

    {{ form_rest(form.need) }}

    {{ form_rest(form) }}

</fieldset>

{{ form_end(form) }}

{% endblock %}

{% endembed %}

src/Laplace/TrainingBundle/Resources/views/Need/delete.html.twig
{% embed 'LaplaceCommonBundle::admin-page.html.twig'
    with { page: [ 'need', 'delete' ] } %}

{% block PageTitle %}{{ parent() }} - Supprimer un besoin{% endblock %}

{% block ContentTitle %}Supprimer un besoin{% endblock %}

{% block ContentBody %}

<p>
    La suppression du besoin <a href="{{ path(laplace_training ~ 'view_need', { 'id': need.id }) }}">{{ need.title }}</a>
    entrainera également la suppression, pour tous les utilisateurs, des
    informations relatives à ce besoin dont les inscriptions,
    les évènements, les discussions et les messages.
    <strong>Attention ! La suppression est irréversible.</strong>
</p>

{{ form_start(delete_form) }}

<fieldset>

    <legend>Supprimer un besoin</legend>

    {{ form_row(delete_form.delete) }}

    {{ form_row(delete_form.do, { 'attr': { 'class': 'btn-danger' } }) }}

    {{ form_rest(delete_form) }}

</fieldset>

{{ form_end(delete_form) }}

{% endblock %}

{% endembed %}

src/Laplace/TrainingBundle/Resources/views/Need/edit.html.twig
{%
    set container = admin ?
        'LaplaceCommonBundle::admin-page.html.twig' :
        'LaplaceCommonBundle::user-page.html.twig'
%}

{% embed container with { page: [ 'need', 'edit' ] } %}

{% block PageTitle %}{{ parent() }} - Modifier un besoin{% endblock %}

{% block ContentTitle %}Modifier un besoin{% endblock %}


{% block ContentBody %}

{{ form_start(edit_form) }}

<fieldset>

    <legend>Modifier un besoin</legend>

    {{ form_rest(edit_form.need) }}

    {{ form_rest(edit_form) }}

</fieldset>

{{ form_end(edit_form) }}

{% endblock %}

{% endembed %}

src/Laplace/TrainingBundle/Resources/views/Need/view-active-subscriptions.html.twig
{% embed 'LaplaceCommonBundle::user-page.html.twig'
    with { page: [ 'need', 'personal' ] } %}

{% block PageTitle %}{{ parent() }} - Besoins personnels{% endblock %}

{% block StyleSheets %}
{{ parent() }}
<style>
    .active-sub-table td,
    .active-sub-table th {
        width: 25%;
    }
</style>
{% endblock %}

{% block ContentTitle %}Besoins personnels{% endblock %}

{% block ContentBody %}

<p>
    Cette page regroupe l'ensemble de vos besoins de formation <strong>non pourvus</strong>,
    classés par date d'ajout (du plus récent au moins récent).

    Cliquez sur le titre d'un besoin pour voir sa description complète ou pour
    <strong>indiquer que ce besoin a été pourvu</strong>.
</p>

<br />

<table class="table table-striped table-bordered active-sub-table">
    {% if subscriptions is empty %}
    <tr>
        <td>Aucun besoin.</td>
    <tr>
    {% endif %}


    {% for sub in subscriptions %}
    <tr>
        <td>
            <span class="badge badge-info" title="{{ sub.type.description }}">{{ sub.type.name }}</span>
            <a href="{{ path('laplace_training_view_need', {id: sub.need.id}) }}">{{ sub.need.title }}</a>
            <span class="pull-right text-right">Ajouté le <strong>{{ sub.subscriptionDate|localizeddate('long', 'short') }}</strong></span>
            <br />
            {% if sub.need.category %}
            <small>{{ sub.need.category.domain.name }} / <small>{{ sub.need.category.name }}</small></small>
            {% else %}
            <small><em>Aucune catégorie</em></small>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>

<p class="pull-right text-right">
    <i class="icon-list"></i>
    <a href="{{ path('laplace_training_all_needs') }}">Voir tous les besoins</a>
</p>

<div class="clearfix"></div>


{% endblock %}

{% endembed %}

src/Laplace/TrainingBundle/Resources/views/Need/view-all.html.twig
{%
    set container = admin ?
        'LaplaceCommonBundle::admin-page.html.twig' :
        'LaplaceCommonBundle::user-page.html.twig'
%}


{% embed container with { page: [ 'need', 'all' ] } %}

{% block PageTitle %}{{ parent() }} - Tous les besoins{% endblock %}

{##############################################################################}

{% block ContentTitle %}Tous les besoins{% endblock %}

{##############################################################################}

{% block Sidebar %}

{{ parent() }}

<li class="divider"></li>

<li class="nav-header">Domaines de connaissances</li>
{% for domain in domains %}
<li>
    <a href="#dom_{{ domain.id }}">{{ domain.name }}</a>
</li>
{% endfor %}

{% endblock %}

{##############################################################################}

{% block ContentBody %}

<p>
    Cliquez sur un besoin de formation pour <strong>voir sa description complète</strong> ou pour <strong>l'ajouter
    à votre liste</strong> de besoins personnels. Si un besoin ne figure pas dans cette
    liste, vous pouvez en <a href="{{ path(laplace_training ~ 'create_need') }}">créer un nouveau</a>.
</p>

{% for domain in domains %}
    <h3 id="dom_{{ domain.id }}">{{ domain.name }}</h3>

    <table class="table table-striped table-bordered table-condensed cat-table">

        {% for cat in domain.categories %}

            {% if groups[cat.id] is defined and groups[cat.id] is not empty %}
                <tr>
                    <th>{{ cat.name }}</th>
                </tr>
                {% for needinfo in groups[cat.id] %}
                    <tr>
                        <td>
                            <span class="badge{% if needinfo.subscriptionCount > 0 %} badge-info{% endif %}"
                                  title="{{needinfo.subscriptionCount}} {% if needinfo.subscriptionCount > 1 %} personnes intéressées {% else %} personne intéressée {% endif %}">{{ needinfo.subscriptionCount }}</span>
                            <a href="{{ path(laplace_training ~ 'view_need', { 'id': needinfo.need.id }) }}">{{ needinfo.need.title }}</a>
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}

        {% endfor %}

    </table>

    <hr />
{% endfor %}

{% if groups[null] is not empty %}
<h3 id="dom_other">Autre</h3>

<table class="table table-striped table-bordered table-condensed cat-table">

    <tr>
        <th>Besoins non classés</th>
    </tr>

    {% for needinfo in groups[null] %}
        <tr>
            <td>
                <span class="badge{% if needinfo.subscriptionCount > 0 %} badge-info {% endif %}"
                      title="Nombre de personnes intéressées">{{ needinfo.subscriptionCount }}</span>
                <a href="{{ path(laplace_training ~ 'view_need', { 'id': needinfo.need.id }) }}">{{ needinfo.need.title }}</a>
            </td>
        </tr>
    {% endfor %}

</table>

<hr />

{% endif %}

<p class="text-right">
    <i class="icon-plus"></i>
    <a href="{{ path(laplace_training ~ 'create_need') }}">Ajouter un besoin qui ne figure pas dans cette liste</a>
</p>

<div class="clearfix"></div>

{% endblock ContentBody %}

{##############################################################################}

{% endembed %}

src/Laplace/TrainingBundle/Resources/views/Need/view.html.twig
{%
    set container = admin ?
        'LaplaceCommonBundle::admin-page.html.twig' :
        'LaplaceCommonBundle::user-page.html.twig'
%}


{% embed container with { page: [ 'need', 'view' ] } %}

{% block PageTitle %}{{ parent() }} - {{ need.title }}{% endblock %}

{% block ContentTitle %}{{ need.title }}{% endblock %}

{##############################################################################}

{% block ContentBody %}

{%
    include 'LaplaceTrainingBundle::category-breadcrumb.html.twig' with {
        reference:
            need,
        link:
            path(laplace_training ~ 'view_need', { 'id': need.id })
    }
%}

<h5>Description du besoin</h5>

{# Auteur #}
{% if admin %}
    <p>
        Par <a href="{{ path(laplace_user ~ 'view_profile', { 'username': need.author.username }) }}">{{ need.author.fullName }}</a>,
        le {{ need.issueDate|localizeddate('long', 'none') }}.
    </p>
{% endif %}

{# Description #}
{% if need.description is empty %}
    <p>
        <em>Aucune description</em>.
    </p>
{% else %}
    <pre>{{ need.description }}</pre>
{% endif %}

{# Outils #}
{% if admin %}
    <p class="text-right">
        <i class="icon-edit"></i>
        <a href="{{ path(laplace_training ~ 'edit_need', { 'id': need.id }) }}">Modifier</a>

        <br />

        <i class="icon-trash"></i>
        <a href="{{ path(laplace_training ~ 'delete_need', { 'id': need.id }) }}">Supprimer</a>
    </p>
{% endif %}



<h5>Inscriptions</h5>
<p class="clearfix">
{% if subscriptions is defined and subscriptions is not empty %}
    <ul>
    {% for subinfo in subscriptions %}
        <li>
            <span class="label label-info">
                {{- subinfo.subscription.type.name -}}
            </span>

            <a href="{{ path(laplace_user ~ 'view_profile', { username: subinfo.user.username }) }}">{{ subinfo.user.fullName }}</a>
            ({{ subinfo.subscription.subscriptionDate|localizeddate('long', 'none') }})
        </li>
    {% endfor %}
    </ul>
{% else %}
    {% set count = need.subscriptions.count() %}
    Ce besoin a été ajouté par
    <span class="badge{% if count > 0 %} badge-info{% endif %}">{{ count }}</span>
    personne(s).
{% endif %}
</p>

{##############################################################################}

<hr />

{##############################################################################}

{% if not admin %}

<h3>Gestion</h3>

    {% if subscription is defined and subscription is not null %}

<p>
    Vous avez ajouté ce besoin à votre liste personnelle
    le <strong>{{ subscription.subscriptionDate|localizeddate('long', 'short') }}</strong>
    avec le type
    <span class="label label-info"
          title="{{ subscription.type.nameWithDescription }}">
        {{- subscription.type.name -}}
    </span>.
</p>

    {% endif %}

{# EDIT FORM #}

    {% if edit_form is defined %}

{{ form_start(edit_form) }}

<fieldset>
    <legend>Modifier</legend>

    <p>
        Ce formulaire vous permet de changer le type de besoin.
    </p>


    {{ form_rest(edit_form) }}

</fieldset>

{{ form_end(edit_form) }}

    {% endif %}



{# SATISFIED FORM #}

    {% if satisfied_form is defined %}

{{ form_start(satisfied_form) }}

<fieldset>
    <legend>Indiquer que le besoin est satisfait</legend>

    <p>
        Ce formulaire vous permet d'indiquer que ce besoin est pourvu.
        <strong>Attention !</strong> Il ne sera alors plus possible de
        modifier cette inscription.
        Les besoins pourvus restent inscrits dans votre historique.
    </p>


    {{ form_rest(satisfied_form) }}

</fieldset>

{{ form_end(satisfied_form) }}

    {% endif %}



{# REMOVE FORM #}

    {% if unsubscribe_form is defined %}

{{ form_start(unsubscribe_form) }}

<fieldset>
    <legend>Retirer ce besoin</legend>

    <p>
        Si vous avez par erreur ajouté ce besoin à votre liste, vous pouvez
        le retirer en utilisant ce formulaire.
        Le besoin disparaîtra également de votre historique.
    </p>

    {{ form_row(unsubscribe_form.unsubscribe) }}

    {{ form_row(unsubscribe_form.do, { "attr": { "class": "btn-danger" } }) }}

    {{ form_rest(unsubscribe_form) }}

</fieldset>

{{ form_end(unsubscribe_form) }}

    {% endif %}



{# SUBSCRIBE FORM #}

    {% if subscribe_form is defined %}

{{ form_start(subscribe_form) }}
<fieldset>
    <legend>Ajouter ce besoin</legend>

{{ form_rest(subscribe_form) }}

</fieldset>
{{ form_end(subscribe_form) }}

    {% endif %}

{##############################################################################}

<hr />

{##############################################################################}

{% endif %}


<h3>Discussions</h3>

{% if not admin %}
<p>
    Cet espace vous permet d'échanger de manière privée avec le correspondant
    formation. Pour poser une question ou ajouter une remarque concernant ce
    besoin, ouvrez une nouvelle discussion à l'aide du formulaire ci-dessous.
    Les messages publiés ne seront visibles que par vous,
    le correspondant formation, et les autres personnes autorisées
    individuellement à participer à la discussion.
</p>
{% endif %}

{% include 'LaplaceTrainingBundle:Thread:table.html.twig' %}

{{ form_start(thread_form) }}

<fieldset>
    <legend>Ouvrir une nouvelle discussion</legend>

    {{ form_rest(thread_form.thread) }}

    {{ form_rest(thread_form.message) }}

    {{ form_rest(thread_form) }}

</fieldset>

{{ form_end(thread_form) }}

{##############################################################################}

{% endblock ContentBody %}

{##############################################################################}

{% endembed %}